<HTML>
	<HEAD>
		<TITLE>
		Form Results
		</TITLE>
	</HEAD>
	<body>
	<?php /*This page receives and handles the data generated by "application.html" */
	print "Applicant's name is $Name.<BR>\n";
	print "Applicant's email is $Email.<BR>\n";
	print "Applicant's academic standing is $AcademicStanding.<BR>\n";
	print "Why applicant wants to join DISC: $Response1.<BR>\n";
	print "Applicant's relevant experience: $Response2.<BR>\n";
	?>
	</body>
</HTML>